src/app.mm
src/menu.mm
src/window.h
src/window.mm

A first pass at adding multiple window support to neovim.app. See #23.
- Adds window.mm to manage each window using a VimWindow
- Each window owns a Vim object and a VimView

Experimental multiple window support

---

src/app.mm
src/client.cc
src/window.mm

When the forked neovim instance exits, emit a message to close the window. This still causes a SIGPIPE, which exits the app, so we also have to ignore SIGPIPE.
Fixes #79

Stop Neovim.app from exiting when one process quits

---

res/nvimrc
src/app.h
src/app.mm
src/menu.h
src/menu.mm
src/redraw.gperf
src/redraw.mm
src/view.h
src/view.mm
src/vimutils.h
src/window.mm

**Functionality:**
Vim menus are implemented in the Mac menu bar. Bar updates when
menus change.
VimScript APIs have been added for Mac-specific features which
until now were hard-coded into the menu:
MacIncreaseFontSize
MacDecreaseFontSize
MacShowFontSelector
MacToggleFullScreen
MacNewWindow
MacCloseTabOrWindow
Mac "Key Equivalents" can be set with:
MacMenu
**Issues:**
Key equivalents are specified in pseudo-Vim notation, parsed in
parseKeyEquivalent. This is still incomplete and cannot parse
much of Vim's notation.
Each Vim instance has its own menu bar, so we should update the
main menu bar when switching windows.

Integration with Vim's menu system

---

src/view.mm

Removed the deprecated NSFontManager delegate as mentioned in Issue #113.

Removed deprecated NSFontManager delegate

---

README.md

Add to install instructions to tap official neovim tap before installing neovim-dot-app

neovim-dot-app depends on a neovim package

---

src/app.mm

doing :pwd when Neovim is launched via finder or with open or spotlight now defaults to the user's home directory instead of '/'.
This should resolve issue #110

Default directory changed to home directory when launched via launchd

---

src/window.mm

Added ! to excommand on write during Save and SaveAs. Any other errors get passed to nvim for display
Fix for the example made in issue #128. Also shows an example of outputting `vim_command` errors to nvim.

Do sav! and w! when doing a menu Save and SaveAs

---

src/window.mm

Re-Sourciing .nvimrc after attaching to the created process. This way anything that does a `has(gui_running)` will be set. 
Fixes the issue in #130

Re-Sourcing .nvimrc after attaching

---

src/input.mm

Hides the mouse cursor when typing in the window. The cursor reappears when the mouse is moved. This seems to be the behavior that most OSX apps have including MacVim, Terminal, and even Chrome. 
This is in regards to Issue #136

Hide the mouse cursor when typing in the window.

---

src/keys.mm

Typing anything with the capslock key on would previously just be inserted as if the capslock key would be off. This is not the usual effect in most text editors (nvim included). Added support for capslock key. 
This should fix issue #138. 
(Note: I had not noticed that the capslock key did not work previously and personally would not mind making that a preference in the future. Thoughts @rogual ?)

Added support for CapsLock key

---

res/nvimrc
src/app.mm
src/input.mm
src/redraw.mm
src/window.h
src/window.mm

Added support for a dialog to popup when closing and the close button to show if the current buffer is modified.
Changes:
- res/nvimrc:
- Added autocmd/function to notify when a buffer has changed inorder
to update documentEdited
- Changed MacCloseTabOrWindow() to do rpcnotify instead of "q".
"q" would fail when more than one file was open, or the document
was edited. This way there will be a popup if buffers need saving.
- Moved MacUpdateTitle to be with the other functions
- src/app.mm
- Added support for closing alert when pressing Cmd-Q.
- src/input.mm
- Set documentEdited when in insertmode.
- src/window.mm:
- Added setting documentEdited when a buffer has changed
- Displays nsalert when there are modified buffers requesting to
save one or more files
- On window closing, the …

Show modified bufffers and prompt to save when closing window with modified buffers

---

README.md

Official instructions for neovim use `brew tap neovim/neovim` now ([see here](https://github.com/neovim/homebrew-neovim/commit/d75f02521c3da0949562dd1fc9aae3bd15064dd8))

Update brew tap command

---

src/app.mm
src/font.mm
src/view.mm

Only show monospace fonts. At launch of application, a temporary collection called "Neovim Monospaced" is created containing only monospaced fonts. When selecting "Show Fonts", this is the only collection that is displayed.
This should fix issue #92.

Create a collection of mono fonts and display it when clicking "Show Fonts"

---

src/redraw.mm
src/view.h
src/view.mm

Added resizeWindow to view.mm to resize the window based on the current size. Calling it from the `resize` action of the `redraw` message. `resize` action is called by neovim when the screen should be resized. 
This should close out #81

Support resizing the window when lines/columns setting is set

---

src/input.mm
src/view.h

Added a preview of the accent that is being entered. Should fix #151. Also removed the `mInsertMode` check so that accents can be entered not just in insertmode but also commandmode. 
@rogual this is the best way that I could find to create a `msgpack::object`. If you know of a better way please let me know.

Added preview when entering accent

---

src/redraw.mm

Fixed vertical line that appears when closing out of an autocomplete window.  This would also happen when there is a vertical split  and one goes up/down a line in the left most window. This was due to an extra pixel being drawn at times when drawing the background. Brought down the width of the drawing of the background and it appears to fix it. 
This should fix #137

Drawing the background rectangle draws an extra pixel

---

gnvim

Quotes `$PWD` to allow for spaces in it.

Fixes #192

---

src/app.mm

The neovim-dot-app process inherits whatever environment variables are
present when it is started. This leads to different behavior when it
is started from the command line or by clicking on the app icon.
Invoking env with -i erases the current environment, before starting a
shell in login mode to probe for the shell's environment. Fixes #84.

Start with an empty environment when setting the shell environment

---

src/window.mm

Resizing window does not always mean that the viewDidEndLiveResize will be called. Calls that method on window resize.
This is for issue #199

Save height/width on window resize

---

SConstruct

Rather than requiring the user to set CFLAGS and LDFLAGS in the event
that msgpack is not installed down `/usr/local` (this happens _e.g._
when someone has a nonstandard Homebrew installation, see #184 for an
example), use SCons' native support for `pkg-config` to set those
variables automatically.
If `pkg-config` is unavailable (perhaps the user has compiled msgpack by
hand), SCons will trap the error and proceed, and the user must set the
build variables to support their installation.

use pkg-config to generate CFLAGS and LDFLAGS

---

gnvim

Leverage `open -W -n` to support `export EDITOR='gnvim -f'` use; passing
the `-f` flag makes the `gnvim` invocation block until you've written
the file, which is the behavior expected by a number of programs that
support the `EDITOR` environment variable.

add support for `-f` flag

---

Makefile

Fixes #212. Can be tested with:
```bash
cat <<-EOF |  grep '$VIM' | sed 's/.*$VIM:[ ]*"\(.*\)"/\1/' | grep -v '$VIM'
System-vimrc-Datei: "\$VIM/sysinit.vim"
Voreinstellung für \$VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
EOF
```

better detection of $VIM fallback

---

README.md

Given you cut a release I figure this makes sense.
Also, `brew install --HEAD neovim` will build with a version of 0.1.3-dev which means `brew install --HEAD neovim-dot-app` will not build against it, so using the release is currently the only way to get this from homebrew (unless I am mistaken).

Remove instructions to install with --HEAD

---

SConstruct

msgpack library got renamed to msgpackc [PR #50534 on homebrew](https://github.com/Homebrew/homebrew/pull/50534)
without fix build fails with:
```
VIM=/usr/local/Cellar/neovim/HEAD/share/nvim NVIM=/usr/local/bin/nvim scons -Q
WARNING: Could not determine exact Neovim version. If your Neovim is not up to date, there may be incompatibilities.
Install file: "res/Info.plist" as "build/Neovim.app/Contents/Info.plist"
clang++ -o build/client.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/client.cc
clang++ -o build/process.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/process.cc
clang++ -o build/rpc.o -c -std=c++11 -stdlib=libc++ -g …
```

update msgpack library name

---

src/input.mm

Improved deadkey recognition. Now it should work on layouts where a modifier key is not required for deadkeys. This pr is for issue #221. I tested it with a greek layout and it seemed to work fine with the `;e` being `έ`. I also tried other random letters and was able to get `άίόύ`.

Allow deadkeys that do not require a modifier key to work

---

src/input.mm

`<C-Tab>` and `<C-S-Tab>` are not passed to the `-keyDown:` event. Added `-performKeyEquivalent:` to capture those keys and pass them on to `-keyDown:` event. 
This is for issue #190

Catch the <C-Tab> & <C-S-Tab> keys and send to keyDown

---

doc/nvim_dot_app.txt
res/nvimrc
src/input.mm
src/keys.h
src/keys.mm
src/tests/main.mm
src/view.h
src/view.mm
src/window.mm

Added macmeta support as requested in #249 and #86. This only translates the Meta/Alt/Option key as such. It does not interpret the Command key as a Meta key. This can be turned on by calling:
```viml
call MacSetMacmeta(1)
```

Added macmeta support

---

src/app.mm

The split environment variable now gets joined with `=` excluding the first value of the array (which is the key). 
This should fix #256

Enviornment value is joined by '='

---

src/app.mm

Environment was setup incorrectly. The shell should be launched with `-l` and have it call `env -i`. 
This should close #235 and fix #84

Fixed setting the environment variables

---

src/app.mm

Fixing issue that was reported in #204. This also happens when running Neovim.app from commandline directly (without using gnvim).

Fixed issue where files may be loaded twice

---

src/client.cc
src/input.mm

The current version of `msgpack` on Homebrew is now 2.0 which deprecates the `unpack` API used in this project. This pull request updates the calls to the reference version of the API.
I noticed this when I was no longer able to build from source on OS X after upgrading msgpack via Homebrew.
See: [Changelog](https://github.com/msgpack/msgpack-c/releases/tag/cpp-2.0.0) and [Commit](https://github.com/msgpack/msgpack-c/pull/453)

Compatability for msgpack-c 2.0

---

src/input.mm
src/main.mm

Frustrated about not being able to build the app on the Sierra beta I took a look at what was needed. Turns it wasn't that much.
This will build without errors and work fine on 10.12. I am unsure about what it means for backwards compatibility though.
Thanks!

macOS 10.12 Sierra support

---

Makefile

Makefile now ignores any newline characters from --version that come from
random newline characters with different locales.
Tested:
- de_DE.UTF-8
- en_US.UTF-8
- zh_TW.UTF-8
- ja_JP.UTF-8
This should be a fix for #282

Fix localized --version ill formated

---

src/view.mm

Fix for #304. Added the value `0` for the key `NSLigatureAttributeName` in `mTextAttrs` to disable drawing ligatures.

Disable ligatures to prevent rendering issues

---

README.md

Since `brew linkapps` is now retired and deprecated, I propose we update the install instructions, since it currently does not work any more.
This PR edits the README to softlink from `/usr/local/opt` to `/Applications`

Update outdated README instructions: replace brew linkapps

---

res/nvimrc

Changed upstream in v0.2.1:
https://github.com/neovim/neovim/commit/93fb7383a330f03bf64ed5558a8e16ea4c742478#diff-0bf1822437d77cb156948e808487340dR115

Fix case in "Split Diff With" to match modern neovim
